import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, Clock, ShieldCheck, Target, AlertTriangle } from 'lucide-react';

export default function BenchmarksPage({ onBack }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // In production, point to actual backend URL. For local dev, hardcode or use relative
    const baseUrl = window.location.hostname === 'localhost' ? 'http://localhost:8000' : 'https://saarthi-production-7b58.up.railway.app';

    fetch(`${baseUrl}/benchmarks`)
      .then(res => res.json())
      .then(json => {
        setData(json);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load benchmarks", err);
        setLoading(false);
      });
  }, []);

  const cardVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: (i) => ({
      opacity: 1,
      y: 0,
      transition: {
        delay: i * 0.1,
        type: 'spring',
        stiffness: 120,
      }
    })
  };

  return (
    <div className="min-h-screen bg-background text-foreground font-sans p-6 sm:p-12 overflow-y-auto">
      <button
        onClick={onBack}
        className="flex items-center gap-2 text-muted-foreground hover:text-foreground mb-8 transition-colors"
      >
        <ArrowLeft size={16} /> Back
      </button>

      <div className="max-w-5xl mx-auto space-y-12">
        {/* Header */}
        <div className="text-center sm:text-left space-y-4">
          <Badge variant="outline" className="text-[#FF9933] border-[#FF9933]/30 bg-[#FF9933]/10">
            Developer Metrics
          </Badge>
          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight">System Benchmarks</h1>
          <p className="text-muted-foreground max-w-2xl text-lg relative">
            Real-time evaluation data generated by running a barrage of queries against our RAG Engine and Scam Detection models.
            <div className="absolute -left-4 -top-4 w-24 h-24 bg-primary/20 blur-3xl rounded-full z-[-1]"></div>
          </p>
          {!loading && data && (
            <p className="text-xs text-muted-foreground font-mono">
              Last Run: {new Date(data.timestamp).toLocaleString()} | Total Samples: {data.total_samples}
            </p>
          )}
        </div>

        {/* Loading State */}
        {loading && (
          <div className="flex justify-center items-center py-20">
            <div className="animate-spin w-8 h-8 border-4 border-primary border-t-transparent rounded-full" />
          </div>
        )}

        {/* Metrics Grid */}
        {!loading && data && (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">

            <motion.div custom={0} initial="hidden" animate="visible" variants={cardVariants} className="bg-card border border-border p-6 rounded-2xl shadow-sm hover:shadow-md transition-shadow relative overflow-hidden">
              <div className="absolute right-0 top-0 w-16 h-16 bg-blue-500/10 rounded-bl-full"></div>
              <div className="flex flex-col gap-4">
                <Target className="text-blue-500 h-6 w-6" />
                <div>
                  <p className="text-muted-foreground text-sm font-medium">Context Accuracy</p>
                  <h3 className="text-3xl font-bold mt-1">{data.metrics.rag_context_accuracy_pct}%</h3>
                </div>
                <p className="text-xs text-muted-foreground">Successful source retrieval and grounded answers</p>
              </div>
            </motion.div>

            <motion.div custom={1} initial="hidden" animate="visible" variants={cardVariants} className="bg-card border border-border p-6 rounded-2xl shadow-sm hover:shadow-md transition-shadow relative overflow-hidden">
              <div className="absolute right-0 top-0 w-16 h-16 bg-green-500/10 rounded-bl-full"></div>
              <div className="flex flex-col gap-4">
                <ShieldCheck className="text-green-500 h-6 w-6" />
                <div>
                  <p className="text-muted-foreground text-sm font-medium">Scam Detection</p>
                  <h3 className="text-3xl font-bold mt-1">{data.metrics.scam_detection_precision_pct}%</h3>
                </div>
                <p className="text-xs text-muted-foreground">Precision of flagging fake schemes or forwards</p>
              </div>
            </motion.div>

            <motion.div custom={2} initial="hidden" animate="visible" variants={cardVariants} className="bg-card border border-border p-6 rounded-2xl shadow-sm hover:shadow-md transition-shadow relative overflow-hidden">
              <div className="absolute right-0 top-0 w-16 h-16 bg-amber-500/10 rounded-bl-full"></div>
              <div className="flex flex-col gap-4">
                <AlertTriangle className="text-amber-500 h-6 w-6" />
                <div>
                  <p className="text-muted-foreground text-sm font-medium">Hallucination Rate</p>
                  <h3 className="text-3xl font-bold mt-1">{"<"} {Math.max(0.1, data.metrics.hallucination_rate_pct)}%</h3>
                </div>
                <p className="text-xs text-muted-foreground">Instances of confidently failing without backing data</p>
              </div>
            </motion.div>

            <motion.div custom={3} initial="hidden" animate="visible" variants={cardVariants} className="bg-card border border-border p-6 rounded-2xl shadow-sm hover:shadow-md transition-shadow relative overflow-hidden">
              <div className="absolute right-0 top-0 w-16 h-16 bg-purple-500/10 rounded-bl-full"></div>
              <div className="flex flex-col gap-4">
                <Clock className="text-purple-500 h-6 w-6" />
                <div>
                  <p className="text-muted-foreground text-sm font-medium">Average Latency</p>
                  <h3 className="text-3xl font-bold mt-1">{data.metrics.average_latency_ms} <span className="text-lg text-muted-foreground">ms</span></h3>
                </div>
                <p className="text-xs text-muted-foreground">End-to-End processing time per query</p>
              </div>
            </motion.div>
          </div>
        )}

        {/* Fallback state if data fails */}
        {!loading && !data && (
          <div className="p-6 bg-red-500/10 border border-red-500/30 rounded-xl text-red-500">
            Error loading benchmarks data. Ensure the backend is running and evaluate_pipeline.py has generated data.
          </div>
        )}

        {/* Detailed Logs Section */}
        {!loading && data && data.detailed_results && (
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5, duration: 0.5 }}
            className="mt-16"
          >
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-6">
              <h2 className="text-2xl font-bold tracking-tight">Detailed Query Logs</h2>
              <Badge variant="outline" className="w-fit">Total Recorded: {data.detailed_results.length}</Badge>
            </div>
            
            <div className="bg-card border border-border rounded-2xl overflow-hidden shadow-sm w-full">
              <div className="overflow-x-auto w-full">
                <table className="w-full text-sm text-left align-middle">
                  <thead className="bg-muted/50 text-muted-foreground">
                    <tr>
                      <th className="px-4 text-xs sm:text-sm sm:px-6 py-4 font-medium whitespace-nowrap">Query</th>
                      <th className="px-4 text-xs sm:text-sm sm:px-6 py-4 font-medium whitespace-nowrap">Intent</th>
                      <th className="px-4 text-xs sm:text-sm sm:px-6 py-4 font-medium whitespace-nowrap">Output Snippet</th>
                      <th className="px-4 text-xs sm:text-sm sm:px-6 py-4 font-medium whitespace-nowrap">Latency</th>
                      <th className="px-4 text-xs sm:text-sm sm:px-6 py-4 font-medium whitespace-nowrap">Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border">
                    {data.detailed_results.map((log, idx) => (
                      <tr key={idx} className="hover:bg-muted/30 transition-colors">
                        <td className="px-4 sm:px-6 py-4 max-w-[150px] sm:max-w-xs truncate" title={log.query}>
                          {log.query}
                        </td>
                        <td className="px-4 sm:px-6 py-4">
                          <span className="bg-primary/10 text-primary px-2 py-1 rounded text-[10px] sm:text-xs whitespace-nowrap inline-block">
                            {log.category.replace('_', ' ')}
                          </span>
                        </td>
                        <td className="px-4 sm:px-6 py-4 max-w-[150px] sm:max-w-sm truncate text-muted-foreground" title={log.output}>
                          {log.output.length > 40 ? log.output.substring(0, 40) + '...' : log.output}
                        </td>
                        <td className="px-4 sm:px-6 py-4 font-mono text-[10px] sm:text-xs whitespace-nowrap">
                          {log.latency_ms}ms
                        </td>
                        <td className="px-4 sm:px-6 py-4 whitespace-nowrap">
                          {log.status === 'Pass' ? (
                            <span className="text-green-500 font-medium flex items-center gap-1"><ShieldCheck size={14}/> Pass</span>
                          ) : log.status === 'Declined' ? (
                            <span className="text-blue-500 flex items-center gap-1"><AlertTriangle size={14}/> Declined</span>
                          ) : (
                            <span className="text-red-500 font-medium flex items-center gap-1"><AlertTriangle size={14}/> {log.status}</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </motion.div>
        )}

      </div>
    </div>
  );
}
